// Code generated by command: go run asm.go -out parse.s -stubs stub.go. DO NOT EDIT.

// +build amd64

package satol

func Parse16SSE(s string) uint64

func Parse16AVX(s string) uint64

func Parse8SSE(s string) uint64

func Parse8AVX(s string) uint64
